### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by Tiffany-Warner** [Pintor-Fall-2018/PYG1#1]
Error shows up after closing the game.
```
Traceback (most recent call last):
  File "C:\Users\tiffy\Desktop\Python Projects\Capstone\PYG1\spectrum.py", line 120, in <module>
    game.getCommands(events)
  File "C:\Users\tiffy\Desktop\Python Projects\Capstone\PYG1\spectrum.py", line 48, in getCommands
    menu.pauseScreen()
  File "C:\Users\tiffy\Desktop\Python Projects\Capstone\PYG1\menu.py", line 35, in pauseScreen
    self.runPauseMenu()
  File "C:\Users\tiffy\Desktop\Python Projects\Capstone\PYG1\menu.py", line 86, in runPauseMenu
    pygame.display.flip()
pygame.error: video system not initialized
```

Relevant part:
```
 line 86, in runPauseMenu
    pygame.display.flip()
pygame.error: video system not initialized
```

**Comment by shaneklumpp** [comment]
sys.exit() needed after pygame.quit() fixes this. Unknown if this is going to cause other errors but this fix works now

**Comment by Tiffany-Warner** [comment]
Closing this for now since it works. Thanks Shane!
