### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by PandaProgrammer** [Pintor-Fall-2018/PYG1#2]
I am trying to do an arcade in python for my final in engineering. Everything is working so far except when I close one game with pygame.quit(), then it throws the following error.

`Traceback (most recent call last):
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\GameDay.py", line 6, in <module>
    class Game:
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\GameDay.py", line 27, in Game
    tetromino.main()
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\tetromino.py", line 169, in main
    showTextScreen('Tetromino')
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\tetromino.py", line 343, in showTextScreen
    while checkForKeyPress() == None:
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\tetromino.py", line 316, in checkForKeyPress
    checkForQuit()
  File "D:\K\Coll\Fa18\ECE\Open Project\GameDay\GameDay\tetromino.py", line 354, in checkForQuit
    pygame.event.post(event) # put the other KEYUP event objects back
pygame.error: video system not initialized`

I cannot sys.exit because my program still needs to run but I cannot seem to keep it going. this error closes my whole program. Any suggestions on how to close without the error?

**Comment by shaneklumpp** [comment]
Hey I am not too sure to be honest if you need to keep other things going. These stackover flows might help you a little more

https://stackoverflow.com/questions/10261774/pygame-error-video-system-not-initialized/10264053

We're also students and are pretty new to pygame as well... but if you maybe can clarify a little more with how your code works and what is happening I would be happy to take a look at it :)

Its possible that your pygame.init() isn't in that function? I had seen other people mention that that could be a source of the video error...
